In [14]:
#LOGISTIC REGRESSION FOR  NON-TEXTUAL DATA
# importing libraries
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

In [15]:
#importing datasets
data_set= pd.read_csv("userdata.csv")

In [16]:
data_set

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [17]:
x= data_set.iloc[:, [2,3]].values
y= data_set.iloc[:, 4].values

In [18]:
from sklearn.model_selection import train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [19]:
print(X_Train)

[[    44  39000]
 [    32 120000]
 [    38  50000]
 [    32 135000]
 [    52  21000]
 [    53 104000]
 [    39  42000]
 [    38  61000]
 [    36  50000]
 [    36  63000]
 [    35  25000]
 [    35  50000]
 [    42  73000]
 [    47  49000]
 [    59  29000]
 [    49  65000]
 [    45 131000]
 [    31  89000]
 [    46  82000]
 [    47  51000]
 [    26  15000]
 [    60 102000]
 [    38 112000]
 [    40 107000]
 [    42  53000]
 [    35  59000]
 [    48  41000]
 [    48 134000]
 [    38 113000]
 [    29 148000]
 [    26  15000]
 [    60  42000]
 [    24  19000]
 [    42 149000]
 [    46  96000]
 [    28  59000]
 [    39  96000]
 [    28  89000]
 [    41  72000]
 [    45  26000]
 [    33  69000]
 [    20  82000]
 [    31  74000]
 [    42  80000]
 [    35  72000]
 [    33 149000]
 [    40  71000]
 [    51 146000]
 [    46  79000]
 [    35  75000]
 [    38  51000]
 [    36  75000]
 [    37  78000]
 [    38  61000]
 [    60 108000]
 [    20  82000]
 [    57  74000]
 [    42  65000]
 [    26  8000

In [20]:
Y_Train

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0], d

In [26]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_Train = sc_X.fit_transform(X_Train)
X_Test = sc_X.transform(X_Test)

In [27]:
# Fitting the Logistic Regression into the Training set
from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(X_Train, Y_Train)

LinearRegression()

In [28]:
# Predicting the test set results

Y_Pred = classifier.predict(X_Test)
Y_Pred

array([ 0.22077932,  0.29079271,  0.30761575,  0.18980184,  0.21081113,
       -0.11863865, -0.03135746,  0.60145703, -0.17271853,  0.50363218,
        0.0736363 ,  0.04354835,  0.28349311,  0.42200223, -0.04969815,
        0.39026593,  0.36868118, -0.08023086,  1.05379649,  0.10238995,
        0.19919457,  0.89472285,  0.37464648,  0.74370764, -0.19430329,
        0.93642735,  0.16745827,  0.1670135 ,  0.3105984 ,  0.2702282 ,
       -0.01529325,  0.37642555,  0.83606461,  0.27574874, -0.05147721,
       -0.23467349, -0.01573801,  0.1570453 ,  0.04221405,  0.52984794,
        0.14466992,  0.37851867,  0.12918118,  0.09464558,  0.66417082,
        0.02850438,  0.38029773,  0.81892751, -0.10657733,  0.72345718,
        1.07614007,  0.08734598,  0.23791642,  0.43584262,  0.99780684,
        0.40771709,  0.17863006,  0.08703191,  0.49887046, -0.22528076,
        0.00691962,  0.84634686, -0.11508053,  0.42720871, -0.30868977,
        1.00510644,  0.06856052,  0.02850438,  0.33249722,  0.47

In [29]:
# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)
cm

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [31]:
from sklearn.metrics import accuracy_score
accuracy =accuracy_score(Y_Test, Y_Pred)
accuracy

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [ ]:
#LOGISTIC REGRESSION FOR TEXTUAL DATA
# importing libraries
